"""Initial migration with async models

Revision ID: 1679c3c15756
Revises: 
Create Date: 2026-02-21 10:25:19.461351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1679c3c15756'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('image_quality_score', sa.Integer(), nullable=True),
    sa.Column('image_quality_label', sa.String(length=50), nullable=True),
    sa.Column('disease_type', sa.String(length=255), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('confidence_percentage', sa.Float(), nullable=False),
    sa.Column('all_predictions', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disease_confidence', 'diagnoses', ['disease_type', 'confidence_percentage'], unique=False)
    op.create_index('idx_user_created', 'diagnoses', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_diagnoses_disease_type'), 'diagnoses', ['disease_type'], unique=False)
    op.create_index(op.f('ix_diagnoses_id'), 'diagnoses', ['id'], unique=False)
    op.create_index(op.f('ix_diagnoses_session_id'), 'diagnoses', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnoses_session_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_disease_type'), table_name='diagnoses')
    op.drop_index('idx_user_created', table_name='diagnoses')
    op.drop_index('idx_disease_confidence', table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
